Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/jammy64"
  config.vm.hostname = "pschemitS"
  config.vm.network "private_network", ip: "192.168.56.110"
  config.vm.network "forwarded_port", guest: 80, host: 8081

  # CPU & RAM
  config.vm.provider "virtualbox" do |vb|
    vb.cpus = 1
    vb.memory = 1024
  end

  # Provisionnement
  config.vm.provision "shell", inline: <<-SHELL
    # Installer K3s server
    curl -sfL https://get.k3s.io | sh -

    # Attendre que K3s soit prêt
    until sudo kubectl get nodes | grep Ready; do sleep 5; done

    # Copier les manifests depuis /vagrant/confs
    cp -r /vagrant/confs /home/vagrant/
    cd /home/vagrant/confs

    # Appliquer tous les manifests (apps + ingress)
    sudo kubectl apply -f .

    echo "Pods et ingress appliqués:"
    sudo kubectl get pods
    sudo kubectl get ingress
  SHELL
end
