Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/jammy64"

  # Server
  config.vm.define "loginS" do |server|
    server.vm.hostname = "loginS"
    server.vm.network "private_network", ip: "192.168.56.110"

    server.vm.provider "virtualbox" do |vb|
      vb.name = "loginS"
      vb.memory = 1024
      vb.cpus = 1
    end

    server.vm.provision "shell", path: "scripts/setup_server.sh"
  end

  # Worker
  config.vm.define "loginSW" do |worker|
    worker.vm.hostname = "loginSW"
    worker.vm.network "private_network", ip: "192.168.56.111"

    worker.vm.provider "virtualbox" do |vb|
      vb.name = "loginSW"
      vb.memory = 512
      vb.cpus = 1
    end

    worker.vm.provision "shell", path: "scripts/setup_worker.sh"
  end
end