Vagrant.configure("2") do |config|
  config.vm.box = "generic/ubuntu2204"

  config.vm.define "loginS" do |server|
    server.vm.hostname = "loginS"
    server.vm.network "private_network", ip: "192.168.56.110"
    server.vm.provider "libvirt" do |lv|
      lv.memory = 1024
      lv.cpus = 1
    end
    server.vm.provision "shell", path: "scripts/setup_server.sh"
  end

  config.vm.define "loginSW" do |worker|
    worker.vm.hostname = "loginSW"
    worker.vm.network "private_network", ip: "192.168.56.111"
    worker.vm.provider "libvirt" do |lv|
      lv.memory = 512
      lv.cpus = 1
    end
    worker.vm.provision "shell", path: "scripts/setup_worker.sh"
  end
end
